---
- name: Create ansible user
  tags:
   - configuration
   - security
  user: name=ansible shell=/bin/bash state=present password={{user_pass}}

- name: Copy Ansible user Authorized Keys
  tags:
    - configuration
    - security
  authorized_key: user=ansible state=present key="{{ lookup('file', '../../../keys/ansible_rsa.pub') }}"

- name: set ansible permissions in /etc/sudoers
  lineinfile: "dest=/etc/sudoers state=present line='ansible ALL=(ALL) NOPASSWD: ALL' validate='/usr/sbin/visudo -cf %s'"
  tags:
    - configuration
    - security
